---
# LFS single server
- hosts: lfsserver
  gather_facts: false
  roles:
    - lfs-common
    - lfs-database
    - { role: lfs
       ,lfs_nginx_domain_name: "{{ host_lfs_nginx_domain_name }}"
       ,lfs_superuser_username: "{{ host_lfs_superuser_username }}" }
