---
# tasks of role: lfs

- name: create lfs database user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name=lfs password=lfs

- name: create lfs database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=lfsdb owner=lfs

- name: allow lfs database login
  sudo: yes
  sudo_user: postgres
  lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf
              regexp='^local\s+all\s+all\s+peer'
              backrefs=yes
              line='local   all             all                                     md5'
  notify: restart postgresql

- name: check if lfs installation package exists
  command: /usr/bin/test -d /tmp/lfs-installer
  register: lfs_install_package_exists
  ignore_errors: yes
  changed_when: lfs_install_package_exists.rc != 0

- name: download lfs install package
  get_url: url=https://pypi.python.org/packages/source/d/django-lfs/django-lfs-installer-0.9.0a1.tar.gz#md5=0f53dfe2f215552e4b7b2a1d4e4d6d62
           dest=/tmp
  when: lfs_install_package_exists.rc != 0

- name: unpack lfs install package
  unarchive: src=/tmp/django-lfs-installer-0.9.0a1.tar.gz dest=/tmp/ copy=no
  when: lfs_install_package_exists.rc != 0

- name: add wsgi to buildout.cfg
  lineinfile: dest=/tmp/lfs-installer/buildout.cfg
              line='wsgi = true'

- name: install step 1 - bootstrap.py
  command: python bootstrap.py
           chdir=/tmp/lfs-installer/
           creates=/tmp/lfs-installer/bin/buildout

- name: install step 2 - bin/buildout
  command: bin/buildout -v
           chdir=/tmp/lfs-installer/
           creates=/tmp/lfs-installer/bin/django

- file: src=/tmp/lfs-installer/bin/django.wsgi
        dest=/tmp/lfs-installer/lfs_project/wsgi.py state=link

- name: install step 3.1 - configure settings
  lineinfile: 
    "dest=/tmp/lfs-installer/lfs_project/settings.py
    regexp=\"\\s+'ENGINE': 'django.db.backends.',\"
    backrefs=yes
    line=\"        'ENGINE': 'django.db.backends.postgresql_psycopg2',\""

- name: install step 3.2 - configure settings
  lineinfile: 
    "dest=/tmp/lfs-installer/lfs_project/settings.py
    regexp=\"\\s+'NAME': '',\"
    backrefs=yes
    line=\"        'NAME': 'lfsdb',\""

- name: install step 3.3 - configure settings
  lineinfile: 
    "dest=/tmp/lfs-installer/lfs_project/settings.py
    regexp=\"\\s+'USER': '',\"
    backrefs=yes
    line=\"        'USER': 'lfs',\""

- name: install step 3.4 - configure settings
  lineinfile: 
    "dest=/tmp/lfs-installer/lfs_project/settings.py
    regexp=\"\\s+'PASSWORD': '',\"
    backrefs=yes
    line=\"        'PASSWORD': 'lfs',\""

- name: install step 3.5 - configure settings
  lineinfile: 
    dest=/tmp/lfs-installer/lfs_project/settings.py
    regexp='^LANGUAGE_CODE'
    backrefs=yes
    line="LANGUAGE_CODE = 'en-ie'"

- name: install step 3.6 - configure settings
  lineinfile: 
    dest=/tmp/lfs-installer/lfs_project/settings.py
    regexp='^LFS_LOCALE'
    backrefs=yes
    line='LFS_LOCALE = "en_IE.UTF-8"'

- name: install step 4.1 - django syncdb
  copy:
    src=initial_data.json
    dest=/tmp/lfs-installer/eggs/Django-1.6.5-py2.7.egg/django/contrib/auth/fixtures/

- name: install step 4.2 - django syncdb
  command: bin/django syncdb --noinput
           chdir=/tmp/lfs-installer/

- name: install step 5 - django migrate
  command: bin/django migrate
           chdir=/tmp/lfs-installer/

- name: install step 6 - django lfs_init
  command: bin/django lfs_init
           chdir=/tmp/lfs-installer/

# TODO: for some reason this fails, run manually
- name: install step 7 - django collectstatic
  command: bin/django collectstatic --noinput
           chdir=/tmp/lfs-installer/

- name: configure nginx 1/3
  file:
    src=/etc/nginx/uwsgi_params
    dest=/tmp/lfs-installer/lfs_project/uwsgi_params
    state=link

- name: configure nginx 2/3
  template:
    src=lfs_nginx.j2
    dest=/tmp/lfs-installer/lfs_project/lfs_nginx.conf

- name: configure nginx 3/3
  sudo: yes
  notify: restart nginx
  file:
    src=/tmp/lfs-installer/lfs_project/lfs_nginx.conf
    dest=/etc/nginx/sites-enabled/lfs_nginx.conf
    state=link

# TODO: run with supervisord
- name: run uwsgi
  command: uwsgi -d ~/lfs.log --socket :8001 --module wsgi
    chdir=/tmp/lfs-installer/lfs_project/
