---
# tasks of role: lfs

- name: check if install package exists
  command: /usr/bin/test -d ~/lfs-installer
  register: lfs_install_package_exists
  ignore_errors: yes
  changed_when: lfs_install_package_exists.rc != 0

- name: download install package
  get_url: url={{ lfs.install_package_url }}
           dest=~
  when: lfs_install_package_exists.rc != 0

- name: unpack lfs install package
  unarchive: src=~/django-lfs-installer-0.9.0a1.tar.gz dest={{ _lfs_root_dir }}/ copy=no
  when: lfs_install_package_exists.rc != 0

- name: add wsgi to buildout.cfg
  lineinfile: dest=~/lfs-installer/buildout.cfg
              line='wsgi = true'

- name: install step 1 - bootstrap.py
  command: python bootstrap.py
           chdir=~/lfs-installer/
           creates=~/lfs-installer/bin/buildout

- name: install step 2.1 - bin/buildout
  command: bin/buildout -v
           chdir=~/lfs-installer/
           creates=~/lfs-installer/bin/django

- name: install step 2.2 - bin/buildout
  file: src=~/lfs-installer/bin/django.wsgi
        dest=~/lfs-installer/lfs_project/wsgi.py state=link

# Note the quoting because of colon (:)
- name: install step 3.1 - configure settings
  lineinfile: 
    "dest=~/lfs-installer/lfs_project/settings.py
    regexp=\"\\s+'ENGINE': 'django.db.backends.',\"
    backrefs=yes
    line=\"        'ENGINE': 'django.db.backends.postgresql_psycopg2',\""

- name: install step 3.2 - configure settings
  lineinfile: 
    "dest=~/lfs-installer/lfs_project/settings.py
    regexp=\"\\s+'NAME': '',\"
    backrefs=yes
    line=\"        'NAME': 'lfsdb',\""

- name: install step 3.3 - configure settings
  lineinfile: 
    "dest=~/lfs-installer/lfs_project/settings.py
    regexp=\"\\s+'USER': '',\"
    backrefs=yes
    line=\"        'USER': 'lfs',\""

- name: install step 3.4 - configure settings
  lineinfile: 
    "dest=~/lfs-installer/lfs_project/settings.py
    regexp=\"\\s+'PASSWORD': '',\"
    backrefs=yes
    line=\"        'PASSWORD': 'lfs',\""

- name: install step 3.5 - configure settings
  lineinfile: 
    dest=~/lfs-installer/lfs_project/settings.py
    regexp='^LANGUAGE_CODE'
    backrefs=yes
    line="LANGUAGE_CODE = 'en-ie'"

- name: install step 3.6 - configure settings
  lineinfile: 
    dest=~/lfs-installer/lfs_project/settings.py
    regexp='^LFS_LOCALE'
    backrefs=yes
    line='LFS_LOCALE = "en_IE.UTF-8"'

- name: install step 4.1 - django syncdb
  copy:
    src=initial_data.json
    dest=~/lfs-installer/eggs/Django-1.6.5-py2.7.egg/django/contrib/auth/fixtures/

- name: install step 4.2 - django syncdb
  command: bin/django syncdb --noinput
           chdir=~/lfs-installer/

- name: install step 5 - django migrate
  command: bin/django migrate
           chdir=~/lfs-installer/

# # TODO: second run fails
# - name: install step 6 - django lfs_init
#   command: bin/django lfs_init
#            chdir=~/lfs-installer/

- name: install step 7 - django collectstatic
  command: bin/django collectstatic --noinput
           chdir=~/lfs-installer/

- name: configure nginx step 1
  notify: restart nginx
  file:
    src=/etc/nginx/uwsgi_params
    dest=~/lfs-installer/lfs_project/uwsgi_params
    state=link

- name: configure nginx step 2
  sudo: yes
  notify: restart nginx
  template:
    src=lfs_nginx.j2
    dest=/etc/nginx/sites-available/lfs_nginx.conf

- name: configure nginx step 3
  sudo: yes
  notify: restart nginx
  file:
    src=/etc/nginx/sites-available/lfs_nginx.conf
    dest=/etc/nginx/sites-enabled/lfs_nginx.conf
    state=link

- name: configure uwsgi
  sudo: yes
  notify: restart uwsgi
  # register: uwsgi_config
  template: src=uwsgi.conf.j2 dest=/etc/init/uwsgi.conf

# TODO: uwsgi stats server: http://uwsgi-docs.readthedocs.org/en/latest/StatsServer.html
# TODO: uwsgitop: https://github.com/unbit/uwsgitop
