---
# vars of role: lfs

lfs_install_package: 'django-lfs-installer-0.9.0a1.tar.gz'

lfs_superuser_username: 'lfsadmin'
lfs_superuser_first_name: ''
lfs_superuser_last_name: ''
lfs_superuser_email: ''

lfs_nginx_domain_name: '{{ inventory_hostname }}'

# role internal vars

_lfs_root_dir: '/home/{{ ansible_ssh_user }}'

lfs:
  root_dir: '{{ _lfs_root_dir }}'
  install_dir: '{{ _lfs_root_dir }}/lfs-installer'
  project_dir: '{{ _lfs_root_dir }}/lfs-installer/lfs_project'

  install_package: '{{ lfs_install_package }}'
  install_package_url: 'https://pypi.python.org/packages/source/d/django-lfs/{{ lfs_install_package }}#md5=0f53dfe2f215552e4b7b2a1d4e4d6d62'

  django_media_path: '{{ _lfs_root_dir }}/lfs-installer/lfs_project/media'
  django_static_path: '{{ _lfs_root_dir }}/lfs-installer/lfs_project/sitestatic'
  django_uwsgi_params: '{{ _lfs_root_dir }}/lfs-installer/lfs_project/uwsgi_params'

  uwsgi_uid: '{{ ansible_ssh_user }}'
  uwsgi_gid: '{{ ansible_ssh_user }}'
